### PR TITLE
unkown -> unknown

### PR DESCRIPTION
**Pull request by curiousleo**
This typo appeared in a few places.

image

### CODE REVIEW

**Review by yannham — APPROVED** [review]

**Comment by yannham** [comment]
Thanks!

**Comment by curiousleo** [comment]
@yannham no problem! Please feel free to merge this PR as you see fit (looks like merge commits are used for PRs in this repo, but I'm not sure). Also feel free to delete this branch afterwards.

**Comment by curiousleo** [comment]
@yannham As of 2021-07-12 08:14 CEST (the timestamp of this comment), the typo screenshotted in the description still appears on https://nickel-lang.org/. Both the website and this PR have been merged now, so I wonder what's going on. The typo no longer exists in `master`, so which branch was the website deployed from?

**Comment by yannham** [comment]
See #366. I'll merge it as soon as the CI is green.

**Pull request merged**
