### PR TITLE
doc: link to typing document

### PR DESCRIPTION
**Pull request by asymmetric**
Adds missing link.

### CODE REVIEW

**Review by yannham — APPROVED** [review]
Thanks! It still needs to be backported to the right branch to be updated on the website. Will do.

**Comment by asymmetric** [comment]
@yannham what's the branch? So I can do it myself for the next cases (which I've already found :sweat_smile:)

**Comment by yannham** [comment]
@asymmetric it's `stable`, but the workflow is a bit constraining, because we also need the change on master. Right now I individually cherry-pick commits on master that update the doc and should be visible on the website as well to backport them on `stable`, then need to update the flake.lock of the website repo, and deploy. Sorry, it just got out of my mind, but it's at least done for this change.

In the general case, unfortunately, I fear you can't do many of these actions by yourself.

**Comment by asymmetric** [comment]
Ok, my takeaway is that it’s better to lump these changes together rather than in many small commits, since the overhead is constant :)

**Pull request merged**
