### PR TITLE
Convert tests to new annotated format, pt. 1

### PR DESCRIPTION
**Pull request by matthew-healy**
This PR converts a bunch of existing tests to the new annotated format introduced in #1298. 

In particular, it rewrites the tests from `contracts_fail`, and then updates every test that already existed as a `.ncl` file to use the new annotations.

The annotation format also changes a little bit, to accommodate additional top-level test configuration (in this case, a `repeat` field to allow tests to be rerun arbitrary numbers of times, to better catch non-deterministic behaviour).

### CODE REVIEW

**Review by vkleen — APPROVED** [review]

**Review by yannham — CHANGES_REQUESTED** [review]
Nothing wrong with this PR, but we're potentially releasing 1.0 today, so let's avoid merging anything except a critical fix to minimize the risk of introducing issues

**Comment by matthew-healy** [comment]
@yannham This doesn't touch anything outside of the `tests` directory, but it's totally your call. :+1:

**Comment by yannham** [comment]
Yeah, I don't really think this PR could have any such impact, it's rather than I was in the middle of the release process (branching, running `nix flake check`), and I didn't want to risk a race condition. We can merge that soon hopefully :)

**Comment by matthew-healy** [comment]
@yannham Could you approve this when you have a sec? I don't think I can merge while there are still changes requested.

**Review by yannham — APPROVED** [review]
Sorry, I wanted to take a deeper look first, but won't have enough time. So I haven't actually reviewed the code in detail, but let's not block this PR.

**Pull request merged**
