### PR TITLE
Use free variables to avoid memory cycles in rec records

### PR DESCRIPTION
**Pull request by Avi-D-coder**
cherry pick of https://github.com/tweag/nickel/pull/529/commits/836e01d17a5f8bdeb568b5489f66ad021cea79f7

### CODE REVIEW

**Comment by yannham** [comment]
This was a hotfix in bench branch. If we are to merge this in master I think we may want to do something a bit more fleshed out because:

1. The current algorithm is quadratic for nested records. That is in the case:
    ```
    {
      foo = { bar =  { baz = exp }
    }
    ```
    We will compute the free variables of exp 4 times, while we could only do it once, if we did this in advance in a bottom-up manner.

2. There are occasions where we already walk the AST. Typically parsing, but also program transformations. We could use one of those passes to avoid doing yet one additional walk to compute the free variables.
3. We may want to actually keep this information of free variables inside either records or revertible thunks (cf #491). Those could be useful for improving the performance of merging in the future too. In fact, we probably have to, because reverting turns a `Record` back to a `RecursiveRecord`, so if we don't want to loose that information and make them leak again, we have to remember it in some way. We could also store it a recursive thunk itself, to avoid polluting all records.

**Comment by Avi-D-coder** [comment]
Something has gotten way slower and is using more memory.
```
nickel on  HEAD (5053b8b) [$] is 📦 v0.1.0 via 🦀 v1.57.0 
❯ cargo criterion --bench lists                       
warning: unused imports: `MultiStringToken`, `NormalToken`, `StringToken`
 --> /home/USER/Work/nickel/target/release/build/nickel-388a991ddea2ff58/out/grammar.rs:9:27
  |
9 | use super::lexer::{Token, NormalToken, StringToken, MultiStringToken};
  |                           ^^^^^^^^^^^  ^^^^^^^^^^^  ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `nickel` (lib) generated 1 warning
    Finished bench [optimized] target(s) in 0.06s
foldr strings 50        time:   [3.5053 ms 3.5261 ms 3.5491 ms]                              
                        change: [+18.327% +19.449% +20.545%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldr deepseq strings 30                                                                             
                        time:   [3.2137 ms 3.2329 ms 3.2642 ms]
                        change: [+6.2012% +7.5072% +8.8218%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldr nums 50           time:   [3.3394 ms 3.3839 ms 3.4462 ms]                           
                        change: [+12.390% +14.431% +17.131%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldr deepseq nums 30   time:   [3.2067 ms 3.2540 ms 3.3221 ms]                                   
                        change: [+3.4746% +5.6397% +7.9905%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldr lists 50          time:   [3.3469 ms 3.3804 ms 3.4406 ms]                            
                        change: [+8.0443% +10.002% +12.213%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldr deepseq lists 30  time:   [3.2046 ms 3.2370 ms 3.2977 ms]                                    
                        change: [+4.3765% +6.7837% +9.3453%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldl strings 50        time:   [3.3737 ms 3.4395 ms 3.5322 ms]                              
                        change: [+13.600% +17.081% +21.031%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldl deepseq strings 30                                                                             
                        time:   [3.2260 ms 3.3271 ms 3.4596 ms]
                        change: [+9.0999% +12.969% +17.341%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldl nums 50           time:   [3.3331 ms 3.4156 ms 3.5370 ms]                           
                        change: [+9.9571% +14.179% +18.756%] (p = 0.00 < 0.05)
                        Performance has regressed.

Benchmarking foldl deepseq nums 30: Collecting 100 samples in estimated 5.0097 s (1400 iterations)^C

nickel on  HEAD (5053b8b) [$] is 📦 v0.1.0 via 🦀 v1.57.0 took 1m58s 
❯ git checkout avi/cherry-pick-rec-opt
Previous HEAD position was 5053b8b Post merge
Switched to branch 'avi/cherry-pick-rec-opt'

nickel on  avi/cherry-pick-rec-opt [$] is 📦 v0.1.0 via 🦀 v1.57.0 
❯ cargo criterion --bench lists       
   Compiling nickel v0.1.0 (/home/USER/Work/nickel)
warning: unused imports: `MultiStringToken`, `NormalToken`, `StringToken`
 --> /home/USER/Work/nickel/target/release/build/nickel-388a991ddea2ff58/out/grammar.rs:9:27
  |
9 | use super::lexer::{Token, NormalToken, StringToken, MultiStringToken};
  |                           ^^^^^^^^^^^  ^^^^^^^^^^^  ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

   Compiling utilities v0.1.0 (/home/USER/Work/nickel/utilities)
warning: `nickel` (lib) generated 1 warning
    Finished bench [optimized] target(s) in 9.31s
foldr strings 50        time:   [3.7676 ms 3.7836 ms 3.8094 ms]                              
                        change: [+6.4277% +7.3005% +8.3353%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldr deepseq strings 30                                                                             
                        time:   [3.6238 ms 3.6477 ms 3.6895 ms]
                        change: [+11.415% +12.830% +14.553%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldr nums 50           time:   [3.7884 ms 3.8368 ms 3.9061 ms]                           
                        change: [+10.789% +13.386% +16.342%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldr deepseq nums 30   time:   [3.6215 ms 3.6527 ms 3.7092 ms]                                   
                        change: [+9.4584% +12.255% +14.730%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldr lists 50          time:   [3.8084 ms 3.8451 ms 3.9123 ms]                            
                        change: [+11.016% +13.748% +16.350%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldr deepseq lists 30  time:   [3.7581 ms 3.7926 ms 3.8592 ms]                                    
                        change: [+14.193% +17.163% +19.436%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldl strings 50        time:   [3.8349 ms 3.8834 ms 3.9658 ms]                              
                        change: [+9.3623% +12.907% +16.150%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldl deepseq strings 30                                                                             
                        time:   [3.6364 ms 3.7231 ms 3.8495 ms]
                        change: [+7.0242% +11.904% +16.829%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldl nums 50           time:   [3.8461 ms 3.9369 ms 4.0705 ms]                           
                        change: [+10.086% +15.260% +20.606%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldl deepseq nums 30   time:   [3.6052 ms 3.7466 ms 3.9325 ms]                                   
                        change: [+24.631% +29.642% +35.736%] (p = 0.00 < 0.05)
                        Performance has regressed.

Benchmarking foldl lists 50: Warming up for 3.0000 s^C

nickel on  avi/cherry-pick-rec-opt [$] is 📦 v0.1.0 via 🦀 v1.57.0 took 1m52s 
❯ git checkout avi/benches-and-flamegraphs-master-2021-12-06
Switched to branch 'avi/benches-and-flamegraphs-master-2021-12-06'
Your branch is up to date with 'origin/avi/benches-and-flamegraphs-master-2021-12-06'.

nickel on  avi/benches-and-flamegraphs-master-2021-12-06 [$] is 📦 v0.1.0 via 🦀 v1.57.0 
❯ cargo criterion --bench lists
   Compiling nickel v0.1.0 (/home/USER/Work/nickel)
warning: unused imports: `MultiStringToken`, `NormalToken`, `StringToken`
  --> /home/USER/Work/nickel/target/release/build/nickel-fe57291e201015bf/out/grammar.rs:11:27
   |
11 | use super::lexer::{Token, NormalToken, StringToken, MultiStringToken};
   |                           ^^^^^^^^^^^  ^^^^^^^^^^^  ^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: field is never read: `ident_kind`
   --> src/eval.rs:327:5
    |
327 |     ident_kind: IdentKind,
    |     ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

   Compiling utilities v0.1.0 (/home/USER/Work/nickel/utilities)
warning: `nickel` (lib) generated 2 warnings
    Finished bench [optimized + debuginfo] target(s) in 10.62s
foldr strings 50        time:   [2.9254 ms 2.9433 ms 2.9660 ms]                              
                        change: [-22.960% -22.207% -21.527%] (p = 0.00 < 0.05)
                        Performance has improved.

foldr deepseq strings 30                                                                             
                        time:   [3.0545 ms 3.0677 ms 3.0910 ms]
                        change: [-17.006% -15.901% -14.936%] (p = 0.00 < 0.05)
                        Performance has improved.

foldr nums 50           time:   [3.0492 ms 3.0846 ms 3.1303 ms]                           
                        change: [-21.303% -19.605% -17.991%] (p = 0.00 < 0.05)
                        Performance has improved.

foldr deepseq nums 30   time:   [2.9483 ms 2.9825 ms 3.0286 ms]                                   
                        change: [-20.065% -18.348% -16.827%] (p = 0.00 < 0.05)
                        Performance has improved.

foldr lists 50          time:   [3.0138 ms 3.0399 ms 3.0813 ms]                            
                        change: [-22.664% -20.940% -19.409%] (p = 0.00 < 0.05)
                        Performance has improved.

foldr deepseq lists 30  time:   [3.0358 ms 3.0957 ms 3.1712 ms]                                    
                        change: [-20.591% -18.376% -16.057%] (p = 0.00 < 0.05)
                        Performance has improved.

foldl strings 50        time:   [2.9907 ms 3.0398 ms 3.1076 ms]                              
                        change: [-23.843% -21.722% -19.411%] (p = 0.00 < 0.05)
                        Performance has improved.

foldl deepseq strings 30                                                                             
                        time:   [2.9692 ms 3.0050 ms 3.0583 ms]
                        change: [-22.223% -19.288% -16.840%] (p = 0.00 < 0.05)
                        Performance has improved.

foldl nums 50           time:   [2.9462 ms 2.9839 ms 3.0441 ms]                           
                        change: [-27.022% -24.207% -21.748%] (p = 0.00 < 0.05)
                        Performance has improved.

foldl deepseq nums 30   time:   [3.0100 ms 3.0458 ms 3.1048 ms]                                   
                        change: [-22.552% -18.704% -15.328%] (p = 0.00 < 0.05)
                        Performance has improved.

foldl lists 50          time:   [3.0073 ms 3.0680 ms 3.1528 ms]                            
                        change: [+0.1374% +3.8892% +7.5059%] (p = 0.03 < 0.05)
                        Change within noise threshold.

foldl deepseq lists 30  time:   [2.9435 ms 2.9777 ms 3.0383 ms]                                    
                        change: [-3.0513% +0.2063% +3.2927%] (p = 0.87 > 0.05)
                        No change in performance detected.

generate normal 50      time:   [5.2240 ms 5.3306 ms 5.4745 ms]                                
                        change: [+2.2669% +5.3083% +8.7058%] (p = 0.00 < 0.05)
                        Performance has regressed.

generate deepseq 30     time:   [11.392 ms 11.444 ms 11.519 ms]                                
                        change: [-3.0066% -0.7006% +1.0241%] (p = 0.58 > 0.05)
                        No change in performance detected.

map normal 50           time:   [3.0022 ms 3.0714 ms 3.1704 ms]                           
                        change: [-2.4779% +1.3557% +5.6454%] (p = 0.54 > 0.05)
                        No change in performance detected.

map deepseq 30          time:   [5.0245 ms 5.1292 ms 5.2812 ms]                            
                        change: [-6.1081% -2.4555% +1.3240%] (p = 0.21 > 0.05)
                        No change in performance detected.

pipe normal 20          time:   [20.599 ms 20.919 ms 21.376 ms]                           
                        change: [-6.9597% -4.3894% -1.5737%] (p = 0.00 < 0.05)
                        Performance has improved.

pipe deepseq 20         time:   [28.193 ms 28.484 ms 29.030 ms]                            
                        change: [-0.2142% +2.3667% +5.1213%] (p = 0.04 < 0.05)
                        Change within noise threshold.

```

**Comment by Avi-D-coder** [comment]
```
nickel on  avi/benches-and-flamegraphs-master-2021-12-06 [$] is 📦 v0.1.0 via 🦀 v1.57.0 
❯ git pull origin master   
nickel on  avi/benches-and-flamegraphs-master-2021-12-06 [$⇡] is 📦 v0.1.0 via 🦀 v1.57.0 
❯ cargo criterion --bench lists
   Compiling nickel v0.1.0 (/home/USER/Work/nickel)
warning: unused imports: `MultiStringToken`, `NormalToken`, `StringToken`
 --> /home/USER/Work/nickel/target/release/build/nickel-388a991ddea2ff58/out/grammar.rs:9:27
  |
9 | use super::lexer::{Token, NormalToken, StringToken, MultiStringToken};
  |                           ^^^^^^^^^^^  ^^^^^^^^^^^  ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

   Compiling utilities v0.1.0 (/home/USER/Work/nickel/utilities)
warning: `nickel` (lib) generated 1 warning
    Finished bench [optimized] target(s) in 8.03s
foldr strings 50        time:   [3.1812 ms 3.2021 ms 3.2305 ms]                              
                        change: [+7.6314% +8.7923% +9.9160%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldr deepseq strings 30                                                                             
                        time:   [3.1989 ms 3.2265 ms 3.2729 ms]
                        change: [+3.8490% +5.1770% +6.7946%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldr nums 50           time:   [3.2545 ms 3.2901 ms 3.3443 ms]                           
                        change: [+4.7240% +6.6625% +8.7761%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldr deepseq nums 30   time:   [3.1907 ms 3.2469 ms 3.3257 ms]                                   
                        change: [+6.3171% +8.8635% +11.503%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldr lists 50          time:   [3.1944 ms 3.2542 ms 3.3412 ms]                            
                        change: [+4.4905% +7.0480% +10.138%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldr deepseq lists 30  time:   [3.3009 ms 3.3718 ms 3.4785 ms]                                    
                        change: [+5.2386% +8.9221% +13.103%] (p = 0.00 < 0.05)
                        Performance has regressed.

foldl strings 50        time:   [3.2180 ms 3.2591 ms 3.3365 ms]                              
                        change: [+4.2551% +7.2133% +10.351%] (p = 0.00 < 0.05)
                        Performance has regressed.

Benchmarking foldl deepseq strings 30: Collecting 100 samples in estimated 5.2338 s (1500 iterations)^C
```

**Comment by Avi-D-coder** [comment]
For the above benchmark logs note that `^C` or a shorter log means I was about to run out of memory.

Performance and memory consumption, have significantly degraded on master.
Some of this maybe due to benchmarks being run now that used to have errors in them, but I believe I checked that at the time for at least a few of those PRs that fixed various benchmarks.

**Comment by yannham** [comment]
Just out of curiosity, could you run the benchmarks several time, and see if the results are stable? For some reasons I had unstable results for some time, like with 10-30% variation of the same version of the code. I think @Acaccia reported not having this problem, so I suspect there's something going on with respect to my system. But just to be sure.

Also, performance have degraded since when? When you opened this PR?

**Comment by Avi-D-coder** [comment]
The `Rc<RichTerm>` change is a major improvement. We are still running out of memory, but not as rapidly.

```
foldr strings 50        time:   [2.2036 ms 2.2056 ms 2.2079 ms]                              
                        change: [-40.027% -39.067% -38.222%] (p = 0.00 < 0.05)
                        Performance has improved.

Benchmarking foldr deepseq strings 30: Collecting 100 samples in estimated 5.0532 s (2200 iterat                                                                                                foldr deepseq strings 30                        
                        time:   [2.1512 ms 2.1568 ms 2.1625 ms]
                        change: [-35.704% -35.060% -34.496%] (p = 0.00 < 0.05)
                        Performance has improved.

foldr nums 50           time:   [2.1544 ms 2.1578 ms 2.1614 ms]                           
                        change: [-39.380% -38.624% -37.949%] (p = 0.00 < 0.05)
                        Performance has improved.

Benchmarking foldr deepseq nums 30: Collecting 100 samples in estimated 5.0935 s (2200 iteration                                                                                                foldr deepseq nums 30   time:   [2.1607 ms 2.1650 ms 2.1692 ms]
                        change: [-35.808% -34.923% -34.116%] (p = 0.00 < 0.05)
                        Performance has improved.

foldr lists 50          time:   [2.1823 ms 2.1865 ms 2.1908 ms]                            
                        change: [-39.255% -38.445% -37.817%] (p = 0.00 < 0.05)
                        Performance has improved.

Benchmarking foldr deepseq lists 30: Collecting 100 samples in estimated 5.1013 s (2200 iteratio                                                                                                foldr deepseq lists 30  time:   [2.1712 ms 2.1743 ms 2.1775 ms]
                        change: [-35.057% -34.139% -33.492%] (p = 0.00 < 0.05)
                        Performance has improved.

foldl strings 50        time:   [2.1593 ms 2.1649 ms 2.1709 ms]                              
                        change: [-39.079% -37.691% -36.660%] (p = 0.00 < 0.05)
                        Performance has improved.

Benchmarking foldl deepseq strings 30: Collecting 100 samples in estimated 5.0727 s (2200 iterat                                                                                                foldl deepseq strings 30                        
                        time:   [2.1634 ms 2.1663 ms 2.1692 ms]
                        change: [-34.039% -32.791% -32.059%] (p = 0.00 < 0.05)
                        Performance has improved.

foldl nums 50           time:   [2.1465 ms 2.1507 ms 2.1549 ms]                           
                        change: [-40.890% -38.957% -37.489%] (p = 0.00 < 0.05)
                        Performance has improved.

Benchmarking foldl deepseq nums 30: Collecting 100 samples in estimated 5.0897 s (2200 iteration                                                                                                foldl deepseq nums 30   time:   [2.1673 ms 2.1717 ms 2.1762 ms]
                        change: [-33.414% -31.856% -30.711%] (p = 0.00 < 0.05)
                        Performance has improved.

foldl lists 50          time:   [2.1567 ms 2.1633 ms 2.1706 ms]                            
                        change: [-33.884% -31.889% -30.245%] (p = 0.00 < 0.05)
                        Performance has improved.

Benchmarking foldl deepseq lists 30: Warming up for 3.0000 s^C
```

**Comment by Avi-D-coder** [comment]
This is quite ugly. It will get somewhat better once `RecRecord` is refactored.
I can think of two ways to make this prettier.
1. We could break the free variables transformation pass out of the traversal.  This would come at a performance cost.
2. Traversal could be idiomatically generalized as a trait with default functions for each term variant. This would require refactoring `Term` to have structs associated with each variant. We will need to do this for `Let` and `RecRecord`, and other variants as they are need in traversals.

For the time being I think ugly probably the best option.

**Pull request closed without merging**
