### PR TITLE
Refactoring operation continuation with Strictness markers on stack

### PR DESCRIPTION
**Pull request by litchipi**
Using strictness markers to save and restore strictness during operation continuations.
Continuation from #433, allows to take care of operation continuation without saving a `prev_strictness` value in the `OperationCont` variants.

### CODE REVIEW

**Review by yannham — APPROVED** [review]
LGTM. I think there is a remaining useless parameters `enriched_strict` still present in the signature of `continuate_operation`. This is the kind of things warnings are for, but I see there is a flood of unused warnings coming from the LSP PRs that makes new ones unnoticeable.

**Comment by litchipi** [comment]
Well the `enriched_strict` argument in `continuate_operation` is still useful as it allows the popped strictness markers to be applied. Also I don't see it in the compiler warnings.

**Comment by yannham** [comment]
Oh, right. But then I think popping strictness markers inside the `continuate_operation` is useless, because it will be done anyway at the very beginning of the next iteration of `eval`?

**Comment by litchipi** [comment]
Indeed, didn't thought about it.
However when I remove everything, it seams that some tests doesn't pass, due to code handling `StrAcc` in         `UnaryOp::ChunksConcat()` operation processing.
I'm investigating it right now

**Comment by litchipi** [comment]
I spotted the problem, but I don't know what to think of the solution I gave..

The arguments for `ChunksConcat` are added to the stack before dealing with the operation. When the `continuate_operation` is called, the stack looks like this:
```                                                                                                                                                                                                                                                              
--- STACK ---
| Cont Op1 ChunksConcat (callstack size 12)             } Term::Op1 evaluation
| Strictness = false                                    }
| StrAcc                                       } Term::StrChunks evaluation
| Thunk                                        }
| Thunk
| Cont Op2First Merge (callstack size 10) 
| Strictness = true 
| Thunk 
| Thunk
| Thunk 
| Cont Op2First Eq (callstack size 7)
| Eq
| Thunk 
| Thunk 
| Cont Op1 BoolOr (callstack size 5) 
| Arg 
| Thunk
| Cont Op1 BoolAnd (callstack size 0)
| Arg
---  END  --- 
```
Then, it pops the `Cont Op1 ChunksConcat` from the top of the stack, and call the `process_unary_operation` that expects the `StrAcc` to follow the operation continuation. But in the meantime the strictness changed (as it's the operator that set the strictness).
To fix it, I allowed the evaluation of `Term::StrChunks` to set the strictness to `true` to prepare for the unary operation in advance, and the tests passes.

**The question is:**   Is this term evaluation always followed by a unary operation ? Will it always require `enriched_strict=true` ? Or by doing this, am I breaking something in the future ?

**Review by yannham — APPROVED** [review]
I see. It does sound reasonable to me. The evaluation of `StrChunks` is always preparing the stack and then calling immediately to `ChunksConcat`. `ChunksConcat` operates on primitive strings, so I can't imagine a case where it shouldn't be strict. It makes sense to set the strictness to true at the first `StrChunks`, instead of waiting the execution of `ChunksConcat`.

**Pull request merged**
