### PR TITLE
Add tutorial on stable branch

### PR DESCRIPTION
**Pull request by rapenne-s**
this is a backport of the tutorial to the stable branch, in order to display it on nickel-lang.org

### CODE REVIEW

**Review by yannham — APPROVED** [review]
Now that I see it again, I think it could be nice to add documentation next to each field of the schema with `doc`. Probably some won't be very useful (like `name`), but if this tutorial is to appear on the website, it has to set the example, and in an ideal world users should have the - almost Pavlovian - reflex to document contracts and contract fields.

**Comment by rapenne-s** [comment]
> Now that I see it again, I think it could be nice to add documentation next to each field of the schema with `doc`. Probably some won't be very useful (like `name`), but if this tutorial is to appear on the website, it has to set the example, and in an ideal world users should have the - almost Pavlovian - reflex to document contracts and contract fields.

I thought about it, but I was afraid to clutter the tutorial. Do you think it should be directly in the contract, or as an extra step to not overwhelm the reader?

**Comment by yannham** [comment]
> I thought about it, but I was afraid to clutter the tutorial. Do you think it should be directly in the contract, or as an extra step to not overwhelm the reader?

Mmh, I see what you mean. Then yes, maybe a last step like "Bonus step", "be nice with your future you, colleagues or open source collaborators and document your contract" could help have smaller, more digestible chunks :+1:

**Comment by yannham** [comment]
@rapenne-s how do you want to proceed? We can merge this first, then add the bonus step. You'll probably have to cherry pick the commit on master as well.

**Comment by rapenne-s** [comment]
that looks fine, I'll also prepare a PR for the website

**Pull request merged**
