### PR TITLE
Use GitHub settings to manage project configuration in-repo

### PR DESCRIPTION
**Pull request by mboes**
See https://github.com/tweag/project.

### CODE REVIEW

**Comment by yannham** [comment]
Do you know how do this settings interact with existing labels?

**Comment by mboes** [comment]
Existing tags that are not listed in this file will be deleted. You should add the ones you want to keep to the list. Possibly using `new_name` (see https://github.com/probot/settings) to make existing labels fit a consistent nomenclature, for example to have an `area: <area>` family of labels for syntax, types, contracts, tools etc (the latter of which should probably be called "cli" for less ambiguity). See https://github.com/bazelbuild/bazel/issues for prior art.

**Comment by garbas** [comment]
Oh I didn't know this exists in GitHub. This is a really nice stuff.

**Comment by mboes** [comment]
It's not native: https://github.com/probot/settings.

**Pull request merged**
