### PR TITLE
Display meta information when providing completion

### LINKED ISSUE #920: Display type, contract or other meta information when performing auto-completion

### PR DESCRIPTION
**Pull request by ebresafegaga**
Closes #920 

Depends on #918

### CODE REVIEW

**Comment by yannham** [comment]
I imagine this PR is dependent on #918 ?

**Comment by ebresafegaga** [comment]
Yes it is

**Comment by yannham** [comment]
Then you can select the other branch as the base branch, to only show the diff with respect to the other branch. It will automatically changes to master once we merged the other PR (if you do that now you'll probably want to rebase on the last version of #918 before)

We also use dpulls: you can write at the end of your description

```
Depends on #918
```

and the CI will block merging until the other PR has been merged, but we can still review in-between :)

**Comment by yannham** [comment]
Update: this PR looks like it needs to be rebased, but @ebresafegaga is off this week.

**Comment by yannham** [comment]
@ebresafegaga should we close this in favor of #966 ?

**Comment by yannham** [comment]
Superseded by #966

**Pull request closed without merging**
