### PR TITLE
What is r.b.c?

### PR DESCRIPTION
**Pull request by blaggacao**
I'm asking this out of discussion here: https://github.com/NixOS/rfcs/pull/42#discussion_r563193452 It has more context. Beware, that my transpilation I/O is lossy.

/cc @roberth Is this a correct interpretation of the issue you raised over there?

### CODE REVIEW

**Comment by roberth** [comment]
I can't really tell what the test is trying to achieve because I couldn't find any documentation for what requirements it tries to test.

The issue I raised in the mentioned comment relates to an 'unintuitive' interaction between option priorities and option nesting in the NixOS module system. I don't see a use of defaults in this example.

Regardless, I'd recommend to document which requirements are being checked in a test case.
That's assuming this example even serves as a test case.

**Comment by blaggacao** [comment]
Wouldn't the requirement be: `r.b.c` is not undefined?

I understand the concept of defaults is orthogonal, since it is only relevant with regard of the ([potentially unbounded](https://github.com/tweag/nickel/issues/240#issuecomment-738752158)) priority of competing values. If I read the context correctly, what seems to matter is that a merge **does** descend down into the tree and performs an in-depth first merge.

Or maybe I's falling short and the question is:

```
let rNest1 = {b=Default({c=10})} in
let rNest2 = (fun x => {a=x; b={d=x}}) 20 in
let r = rNest1 & rNest2 in
r.b.c # what is r.b.c?
```

**Comment by yannham** [comment]
The sources in `examples/xxx.ncl` are examples, not tests, and they are terribly outdated (they need to be updated soon). Note also that since #266, the examples can be rewritten as:
```
let rNest1 = {
    b | default = {c = 10}
} in
...
```

Indeed, `r.b.c` is undefined, because `default` works the same as NixOS `lib.mkDefault`. One needs to write `{b = {c | default = 10}}` to have it defined in the final result.

If I understand correctly, the issue is when you want to specify a set of "leaf" defaults  (that is, of the latter form `{b = { c | default = ... }}` but without knowing the content  `{c = 10}` of the record beforehand, and without having to trust the user providing the record to put the required `default` attributes everywhere? In that case, I guess you would need either `default` or another specific attribute (say, `recDefault`) to be automatically pushed downward the leafs during evaluation.

However it's not clear to me if it's a general issue that should be solved in the language, or just a consequence of some design choices on the NixOS module system way of defining default.

In any case, this should be an issue rather than a PR. Once the subject is clear, let's move it there.

**Comment by blaggacao** [comment]
I was acting on behalf of the messanger not the interested party role with a faint 20% understanding of the issue. Hence, I figured fiddling with an example via draft PR would be the best paper on which to IO the message.

I think you understood the use case better than me, already, which is pretty rewarding for _just a messager_. 😄 

> However it's not clear to me if it's a general issue that should be solved in the language, or just a consequence of some design choices on the NixOS module system way of defining default.

10000ft flight level: a "leafy" default would constitute no more than defaulting semantic sugar for a common data structure, that is a _nested object_.

It might be a terciary concern, though, for a language feature. I'm closing as a means to give room to a proper issue, should that call be made.

**Comment by roberth** [comment]
I must have been confused about who the interested party is. I was trying to support @blaggacao.

@yannham you seem to have a good understanding of the interaction between defaults and nesting.

@ me if anyone has questions for me.

**Comment by blaggacao** [comment]
> I must have been confused about who the interested party is. 

I think the interested party is posterity on their behalf we serve. 😉

**Comment by blaggacao** [comment]
Second guessing myself: shall I formulate that issue? I'd be happy to give it a try (disclaimer: potentially lossy IO ahead :wink:).

**Comment by yannham** [comment]
If you feel like it, please do! Thanks for contributing.

**Pull request closed without merging**
